server:
    servlet:
        # 应用根目录
        context-path: /
    # 应用端口
    port: 9001
spring:
    cloud:
        gateway:
            routes:
                -   id: company-route
                    uri: http://192.168.1.152:5602
                    predicates:
                        - Path=/company/**
                    filters:
                        - StripPrefix=1
                -   id: project-route
                    uri: http://192.168.1.152:5601
                    predicates:
                        - Path=/project/**
                    filters:
                        - StripPrefix=1
                -   id: chat-route
                    uri: http://192.168.1.152:5606
                    predicates:
                        - Path=/chat/**
                    filters:
                        - StripPrefix=1
                -   id: chat-ws-route
                    uri: ws://192.168.1.152:5606
                    predicates:
                        - Path=/chat/websocket/**
                    filters:
                        - StripPrefix=1
            discovery:
                locator:
                    # DiscoveryClient gateway integration 网关集成开启
                    enabled: true
                    lowerCaseServiceId: true
            # 跨域
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedHeaders: "*"
                        allowedOrigins: "*"
                        exposedHeaders:
                            - content-type
                        allowCredentials: true
                        allowedMethods:
                            - GET
                                POST
                                DELETE
                                PUT
                                OPTION
company-server-url: http://192.168.1.152:5602