server:
    servlet:
        session:
            timeout: 36000s
    # 应用端口
    port: 5601
    compression:
        # 开启压缩
        enabled: true
        # 压缩最小大小(byte)
        min-response-size: 524288
        # 压缩数据类型
        mime-types: application/json
spring:
    thymeleaf:
        mode: HTML
        #开启缓存
        cache: false
    servlet:
        multipart:
            #文件请求最大值
            max-file-size: 100MB
            #网络请求最大数据
            max-request-size: 100MB